FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04

RUN apt-get update --fix-missing && apt-get -qq install -y --no-install-recommends \
        apt-utils \
        python3 \
        python3-dev \
        python3-pip \
        python3-setuptools \
        git curl ca-certificates bzip2 cmake tree htop bmon iotop g++ \
		libglib2.0-0 libsm6 libxext6 libxrender-dev libssl-dev openssl \
		&& \
    rm -rf /var/lib/apt/lists/* && \
    apt-get update

RUN pip3 install --upgrade pip

RUN apt-get install -y libssl-dev openssl
RUN pip install tensorflow-gpu==1.15
RUN pip install tensorflow-graphics-gpu
RUN pip install torch
RUN pip install tensorboardX
RUN pip install torchvision
RUN pip install scipy
RUN pip install future
RUN pip install tqdm
RUN pip install opencv-python

####################
# Jupyter Notebook #
####################

RUN pip install jupyterlab
RUN pip install notebook
RUN pip install jupyter_contrib_nbextensions && \
    jupyter contrib nbextension install --user

RUN jupyter nbextension enable autosavetime/main --sys-prefix &&\
    jupyter nbextension enable codefolding/main --sys-prefix && \
    jupyter nbextension enable collapsible_headings/main --sys-prefix && \
    jupyter nbextension enable datestamper/main --sys-prefix && \
    jupyter nbextension enable execute_time/ExecuteTime --sys-prefix && \
    jupyter nbextension enable freeze/main --sys-prefix && \
    jupyter nbextension enable highlight_selected_word/main --sys-prefix && \
    jupyter nbextension enable hinterland/hinterland --sys-prefix && \
    jupyter nbextension enable printview/main --sys-prefix && \
    jupyter nbextension enable scratchpad/main --sys-prefix && \
    jupyter nbextension enable snippets_menu/main --sys-prefix && \
    jupyter nbextension enable splitcell/splitcell --sys-prefix && \
    jupyter nbextension enable toc2/main --sys-prefix && \
    jupyter nbextension enable toggle_all_line_numbers/main --sys-prefix && \
    jupyter nbextension enable varInspector/main --sys-prefix && \
    jupyter nbextension enable zenmode/main --sys-prefix


#########
# Alias #
#########
RUN echo alias 'python="python3"' >> ~/.bashrc

WORKDIR /
ENV SRC /src
