jupyter nbextension enable autosavetime/main --sys-prefix
jupyter nbextension enable codefolding/main --sys-prefix
jupyter nbextension enable collapsible_headings/main --sys-prefix
jupyter nbextension enable datestamper/main --sys-prefix
jupyter nbextension enable execute_time/ExecuteTime --sys-prefix
jupyter nbextension enable freeze/main --sys-prefix
jupyter nbextension enable highlight_selected_word/main --sys-prefix
jupyter nbextension enable printview/main --sys-prefix
jupyter nbextension enable scratchpad/main --sys-prefix
jupyter nbextension enable snippets_menu/main --sys-prefix
jupyter nbextension enable splitcell/splitcell --sys-prefix
jupyter nbextension enable toc2/main --sys-prefix
jupyter nbextension enable toggle_all_line_numbers/main --sys-prefix
jupyter nbextension enable varInspector/main --sys-prefix
jupyter nbextension enable zenmode/main --sys-prefix
